//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMineNew.Resources.Shaders {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Shaders {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Shaders() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("CMineNew.Resources.Shaders.Shaders", typeof(Shaders).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string block_vertex {
            get {
                return ResourceManager.GetString("block_vertex", resourceCulture);
            }
        }
        
        internal static string block_fragment {
            get {
                return ResourceManager.GetString("block_fragment", resourceCulture);
            }
        }
        
        internal static string tall_grass_vertex {
            get {
                return ResourceManager.GetString("tall_grass_vertex", resourceCulture);
            }
        }
        
        internal static string tall_grass_fragment {
            get {
                return ResourceManager.GetString("tall_grass_fragment", resourceCulture);
            }
        }
        
        internal static string slab_vertex {
            get {
                return ResourceManager.GetString("slab_vertex", resourceCulture);
            }
        }
        
        internal static string slab_fragment {
            get {
                return ResourceManager.GetString("slab_fragment", resourceCulture);
            }
        }
        
        internal static string water_vertex {
            get {
                return ResourceManager.GetString("water_vertex", resourceCulture);
            }
        }
        
        internal static string water_fragment {
            get {
                return ResourceManager.GetString("water_fragment", resourceCulture);
            }
        }
        
        internal static string water_water_fragment {
            get {
                return ResourceManager.GetString("water_water_fragment", resourceCulture);
            }
        }
        
        internal static string block_lines_vertex {
            get {
                return ResourceManager.GetString("block_lines_vertex", resourceCulture);
            }
        }
        
        internal static string block_lines_fragment {
            get {
                return ResourceManager.GetString("block_lines_fragment", resourceCulture);
            }
        }
        
        internal static string post_render_vertex {
            get {
                return ResourceManager.GetString("post_render_vertex", resourceCulture);
            }
        }
        
        internal static string post_render_fragment {
            get {
                return ResourceManager.GetString("post_render_fragment", resourceCulture);
            }
        }
        
        internal static string post_render_water_fragment {
            get {
                return ResourceManager.GetString("post_render_water_fragment", resourceCulture);
            }
        }
        
        internal static string ssao_vertex {
            get {
                return ResourceManager.GetString("ssao_vertex", resourceCulture);
            }
        }
        
        internal static string ssao_fragment {
            get {
                return ResourceManager.GetString("ssao_fragment", resourceCulture);
            }
        }
        
        internal static string ssao_blur_vertex {
            get {
                return ResourceManager.GetString("ssao_blur_vertex", resourceCulture);
            }
        }
        
        internal static string ssao_blur_fragment {
            get {
                return ResourceManager.GetString("ssao_blur_fragment", resourceCulture);
            }
        }
        
        internal static string directional_light_vertex {
            get {
                return ResourceManager.GetString("directional_light_vertex", resourceCulture);
            }
        }
        
        internal static string directional_light_fragment {
            get {
                return ResourceManager.GetString("directional_light_fragment", resourceCulture);
            }
        }
        
        internal static string flash_light_vertex {
            get {
                return ResourceManager.GetString("flash_light_vertex", resourceCulture);
            }
        }
        
        internal static string flash_light_fragment {
            get {
                return ResourceManager.GetString("flash_light_fragment", resourceCulture);
            }
        }
        
        internal static string point_light_vertex {
            get {
                return ResourceManager.GetString("point_light_vertex", resourceCulture);
            }
        }
        
        internal static string point_light_fragment {
            get {
                return ResourceManager.GetString("point_light_fragment", resourceCulture);
            }
        }
        
        internal static string static_text_vertex {
            get {
                return ResourceManager.GetString("static_text_vertex", resourceCulture);
            }
        }
        
        internal static string static_text_fragment {
            get {
                return ResourceManager.GetString("static_text_fragment", resourceCulture);
            }
        }
        
        internal static string pointer_vertex {
            get {
                return ResourceManager.GetString("pointer_vertex", resourceCulture);
            }
        }
        
        internal static string pointer_fragment {
            get {
                return ResourceManager.GetString("pointer_fragment", resourceCulture);
            }
        }
        
        internal static string sky_box_vertex {
            get {
                return ResourceManager.GetString("sky_box_vertex", resourceCulture);
            }
        }
        
        internal static string sky_box_fragment {
            get {
                return ResourceManager.GetString("sky_box_fragment", resourceCulture);
            }
        }
        
        internal static string loop_delay_viewer_vertex {
            get {
                return ResourceManager.GetString("loop_delay_viewer_vertex", resourceCulture);
            }
        }
        
        internal static string loop_delay_viewer_fragment {
            get {
                return ResourceManager.GetString("loop_delay_viewer_fragment", resourceCulture);
            }
        }
        
        internal static string gui_2d_element_vertex {
            get {
                return ResourceManager.GetString("gui_2d_element_vertex", resourceCulture);
            }
        }
        
        internal static string gui_2d_element_fragment {
            get {
                return ResourceManager.GetString("gui_2d_element_fragment", resourceCulture);
            }
        }
        
        internal static string gui_block_element_vertex {
            get {
                return ResourceManager.GetString("gui_block_element_vertex", resourceCulture);
            }
        }
        
        internal static string gui_block_element_fragment {
            get {
                return ResourceManager.GetString("gui_block_element_fragment", resourceCulture);
            }
        }
    }
}
