//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMineNew.Resources.Shaders {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Shaders {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Shaders() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CMineNew.Resources.Shaders.Shaders", typeof(Shaders).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #version 400 core
        ///
        ///uniform vec4 background;
        ///
        ///layout (location = 0) out vec3 gPosition;
        ///layout (location = 1) out vec4 gNormal;
        ///layout (location = 2) out vec4 gAmbient;
        ///layout (location = 3) out vec4 gDiffuse;
        ///layout (location = 4) out vec4 gSpecular;
        ///
        ///void main() {
        ///    gAmbient = background;
        ///    gDiffuse = vec4(0);
        ///    gSpecular = vec4(0);
        ///    gPosition = vec3(0);
        ///    gNormal = vec4(0);
        ///}.
        /// </summary>
        internal static string background_fragment {
            get {
                return ResourceManager.GetString("background_fragment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #version 400 core
        ///
        ///layout (location = 0) in vec2 position;
        ///
        ///void main () {
        ///    gl_Position = vec4(position.xy, -1, 1);
        ///}
        ///.
        /// </summary>
        internal static string background_vertex {
            get {
                return ResourceManager.GetString("background_vertex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #version 400 core
        ///
        ///in vec3 fragPos, fragNormal;
        ///in vec2 fragTexCoord;
        ///in vec4 fragColorFilter;
        ///
        ///layout (location = 0) out vec3 gPosition;
        ///layout (location = 1) out vec4 gNormal;
        ///layout (location = 2) out vec4 gAmbient;
        ///layout (location = 3) out vec4 gDiffuse;
        ///layout (location = 4) out vec4 gSpecular;
        ///
        ///uniform sampler2D sampler;
        ///
        ///void main() {
        ///    vec4 texture = texture(sampler, fragTexCoord);
        ///    if (texture.w &lt; 0.1) discard;
        ///
        ///    if (texture.r == texture.g &amp;&amp; texture.r == texture.b &amp;&amp; fra [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string block_fragment {
            get {
                return ResourceManager.GetString("block_fragment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #version 400 core
        ///
        ///in vec3 fragPos;
        ///
        ///layout (location = 0) out vec3 gPosition;
        ///layout (location = 1) out vec4 gNormal;
        ///layout (location = 2) out vec4 gAmbient;
        ///layout (location = 3) out vec4 gDiffuse;
        ///layout (location = 4) out vec4 gSpecular;
        ///
        ///void main() {
        ///    gAmbient = vec4(0, 0, 0, 1);
        ///    gDiffuse = vec4(0, 0, 0, 1);
        ///    gSpecular = vec4(0, 0, 0, 1);
        ///    gPosition = fragPos;
        ///    gNormal = vec4(0, 1, 0, 0);
        ///}.
        /// </summary>
        internal static string block_lines_fragment {
            get {
                return ResourceManager.GetString("block_lines_fragment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #version 400 core
        ///
        ///layout (location = 0) in vec3 position;
        ///
        ///out vec3 fragPos;
        ///
        ///uniform mat4 viewProjection;
        ///uniform vec3 worldPosition;
        ///
        ///void main () {
        ///    mat4 model = mat4(1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, worldPosition.x, worldPosition.y, worldPosition.z, 1);
        ///    vec4 modelPosition = model * vec4(position, 1);
        ///    gl_Position = viewProjection * modelPosition;
        ///    gl_Position.z -= 0.001;
        ///    fragPos = modelPosition.xyz;
        ///}
        ///.
        /// </summary>
        internal static string block_lines_vertex {
            get {
                return ResourceManager.GetString("block_lines_vertex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #version 400 core
        ///
        ///layout (location = 0) in vec3 position;
        ///layout (location = 1) in vec3 normal;
        ///layout (location = 2) in vec2 texturePosition;
        ///layout (location = 3) in vec3 worldPosition;
        ///layout (location = 4) in vec4 textureArea;
        ///layout (location = 5) in vec4 blockColorFilter;
        ///
        ///out vec3 fragPos, fragNormal;
        ///out vec2 fragTexCoord;
        ///out vec4 fragColorFilter;
        ///
        ///uniform mat4 viewProjection;
        ///
        ///void main () {
        ///    mat4 model = mat4(1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, worldPosition.x, worldPosition.y [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string block_vertex {
            get {
                return ResourceManager.GetString("block_vertex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #version 400 core
        ///
        ///in vec3 fragPos;
        ///in vec2 fragTexCoord;
        ///
        ///out vec4 FragColor;
        ///
        ///uniform sampler2D pointer;
        ///
        ///void main() {
        ///    vec4 texture = texture(pointer, fragTexCoord);
        ///    if(texture.w &lt; 0.1) discard;
        ///    FragColor = vec4(1);
        ///}.
        /// </summary>
        internal static string pointer_fragment {
            get {
                return ResourceManager.GetString("pointer_fragment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #version 400 core
        ///
        ///layout (location = 0) in vec3 position;
        ///layout (location = 1) in vec3 normal;
        ///layout (location = 2) in vec2 texturePosition;
        ///
        ///out vec3 fragPos;
        ///out vec2 fragTexCoord;
        ///
        ///uniform float aspectRatio;
        ///
        ///void main () {
        ///    gl_Position = vec4(position, 1);
        ///    gl_Position.y *= aspectRatio;
        ///    fragTexCoord = texturePosition;
        ///}
        ///.
        /// </summary>
        internal static string pointer_vertex {
            get {
                return ResourceManager.GetString("pointer_vertex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #version 400 core
        ///
        ///in vec2 fragTexCoords;
        ///out vec4 FragColor;
        ///
        ///uniform sampler2D gAmbient;
        ///uniform sampler2D gDiffuse;
        ///uniform sampler2D gSpecular;
        ///uniform sampler2D gAmbientBrightness;
        ///uniform sampler2D gDiffuseBrightness;
        ///uniform sampler2D gSpecularBrightness;
        ///
        ///uniform float ambientStrength;
        ///uniform vec3 ambientColor;
        ///
        ///vec3 calculateGlobalAmbient (vec3 modelAmbientColor) {
        ///    return ambientStrength * ambientColor * modelAmbientColor;
        ///}
        ///
        ///vec3 toLdr (vec3 color) {
        ///    float exposure = 1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string post_render_fragment {
            get {
                return ResourceManager.GetString("post_render_fragment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #version 400 core
        ///
        ///layout (location = 0) in vec2 position;
        ///layout (location = 1) in vec2 texturePosition;
        ///
        ///out vec2 fragTexCoords;
        ///
        ///void main () {
        ///    gl_Position = vec4(position.xy, 0, 1);
        ///    fragTexCoords = texturePosition;
        ///}
        ///.
        /// </summary>
        internal static string post_render_vertex {
            get {
                return ResourceManager.GetString("post_render_vertex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #version 400 core
        ///
        ///out vec4 FragColor;
        ///
        ///in vec2 fragTextCoord;
        ///in vec4 fragColor;
        ///
        ///uniform float relative;
        ///uniform sampler2D textureSampler;
        ///
        ///void main() {
        ///    vec4 color = texture(textureSampler, fragTextCoord) * fragColor;
        ///    if(color.w &lt; 0.01) discard;
        ///    FragColor = color;
        ///}.
        /// </summary>
        internal static string static_text_fragment {
            get {
                return ResourceManager.GetString("static_text_fragment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #version 400 core
        ///
        ///layout (location = 0) in vec3 position;
        ///layout (location = 1) in vec3 normal;
        ///layout (location = 2) in vec2 texturePosition;
        ///
        ///layout (location = 3) in vec2 minPosition;
        ///layout (location = 4) in vec2 size;
        ///layout (location = 5) in vec4 color;
        ///layout (location = 6) in vec4 textureCoords;
        ///
        ///out vec2 fragTextCoord;
        ///out vec4 fragColor;
        ///
        ///uniform mat4 model, view, projection;
        ///
        ///void main () {
        ///    gl_Position = vec4(position.xy * size, 0.9f, 1.0) + vec4(minPosition, 0, 0);
        ///    fra [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string static_text_vertex {
            get {
                return ResourceManager.GetString("static_text_vertex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #version 400 core
        ///
        ///in vec3 fragPos, fragNormal;
        ///in vec2 fragTexCoord;
        ///in vec4 fragColorFilter;
        ///
        ///layout (location = 0) out vec3 gPosition;
        ///layout (location = 1) out vec4 gNormal;
        ///layout (location = 2) out vec4 gAmbient;
        ///layout (location = 3) out vec4 gDiffuse;
        ///layout (location = 4) out vec4 gSpecular;
        ///
        ///uniform sampler2D sampler;
        ///
        ///void main() {
        ///    vec4 texture = texture(sampler, fragTexCoord);
        ///    if (texture.w &lt; 0.1) discard;
        ///
        ///    if (texture.r == texture.g &amp;&amp; texture.r == texture.b &amp;&amp; fra [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string water_fragment {
            get {
                return ResourceManager.GetString("water_fragment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #version 400 core
        ///
        ///layout (location = 0) in vec3 position;
        ///layout (location = 1) in vec3 normal;
        ///layout (location = 2) in vec2 texturePosition;
        ///layout (location = 3) in vec3 worldPosition;
        ///layout (location = 4) in vec4 textureArea;
        ///layout (location = 5) in vec4 blockColorFilter;
        ///
        ///out vec3 fragPos, fragNormal;
        ///out vec2 fragTexCoord;
        ///out vec4 fragColorFilter;
        ///
        ///uniform mat4 viewProjection;
        ///
        ///void main () {
        ///    mat4 model = mat4(1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, worldPosition.x, worldPosition.y [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string water_vertex {
            get {
                return ResourceManager.GetString("water_vertex", resourceCulture);
            }
        }
    }
}
