//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMineNew.Resources.Textures {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Textures {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Textures() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("CMineNew.Resources.Textures.Textures", typeof(Textures).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static byte[] pointer {
            get {
                object obj = ResourceManager.GetObject("pointer", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] gui_hotbar {
            get {
                object obj = ResourceManager.GetObject("gui_hotbar", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] sky_box_back {
            get {
                object obj = ResourceManager.GetObject("sky_box_back", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] sky_box_bottom {
            get {
                object obj = ResourceManager.GetObject("sky_box_bottom", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] sky_box_front {
            get {
                object obj = ResourceManager.GetObject("sky_box_front", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] sky_box_left {
            get {
                object obj = ResourceManager.GetObject("sky_box_left", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] sky_box_right {
            get {
                object obj = ResourceManager.GetObject("sky_box_right", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] sky_box_top {
            get {
                object obj = ResourceManager.GetObject("sky_box_top", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] stone {
            get {
                object obj = ResourceManager.GetObject("stone", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] dirt {
            get {
                object obj = ResourceManager.GetObject("dirt", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] grass_side {
            get {
                object obj = ResourceManager.GetObject("grass_side", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] grass_top {
            get {
                object obj = ResourceManager.GetObject("grass_top", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] water {
            get {
                object obj = ResourceManager.GetObject("water", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] tall_grass {
            get {
                object obj = ResourceManager.GetObject("tall_grass", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] bricks {
            get {
                object obj = ResourceManager.GetObject("bricks", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] oak_log_side {
            get {
                object obj = ResourceManager.GetObject("oak_log_side", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] oak_log_top {
            get {
                object obj = ResourceManager.GetObject("oak_log_top", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] oak_leaves {
            get {
                object obj = ResourceManager.GetObject("oak_leaves", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] sand {
            get {
                object obj = ResourceManager.GetObject("sand", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] torch {
            get {
                object obj = ResourceManager.GetObject("torch", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
